### ISSUE TITLE
AttributeError: __enter__

### ISSUE THREAD

**Issue by Onefivefournine** [jay3332/pilmoji#4]
Code from readme is not working

```
from pilmoji import Pilmoji
from PIL import Image, ImageFont


my_string = '''
Hello, world! 👋 Here are some emojis: 🎨 🌊 😎
I also support Discord emoji: <:rooThink:596576798351949847>
'''

with Image.new('RGB', (550, 80), (255, 255, 255)) as image:
    font = ImageFont.truetype('arial.ttf', 24)

    with Pilmoji(image) as pilmoji:
        pilmoji.text((10, 10), my_string.strip(), (0, 0, 0), font)

    image.show()
```

Output:
```
Traceback (most recent call last):
  File "/path/to/that/script.py", line 14, in <module>
    pilmoji.text((10, 10), my_string.strip(), (0, 0, 0), font)
  File "/usr/local/lib/python3.9/site-packages/pilmoji/core.py", line 299, in text
    stream = self._get_emoji(content)
  File "/usr/local/lib/python3.9/site-packages/pilmoji/core.py", line 154, in _get_emoji
    if stream := self.source.get_emoji(emoji):
  File "/usr/local/lib/python3.9/site-packages/pilmoji/source.py", line 166, in get_emoji
    return BytesIO(self.request(url))
  File "/usr/local/lib/python3.9/site-packages/pilmoji/source.py", line 116, in request
    with self._requests_session.get(url, **self.REQUEST_KWARGS) as response:
AttributeError: __enter__
```

$ python3 -V
Python 3.9.8

OS:
MacOS BigSur 11.6

**Comment by Onefivefournine** [comment]
Managed to get it working by uninstalling `pilmoji` and `requests`, and then installing `pilmoji[requests]`
I guess the source code should be modified to support newer version of requests

**Comment by jay3332** [comment]
Issue has gone stale. It appears pilmoji does not work with older versions of requests
